language: node_js
node_js:
  - "0.11"
env:
  - NODE_ENV=test
services:
  - mongodb
  - redis-server
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

// angular-seed part
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - npm install --quiet -g protractor
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start
script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - webdriver-manager update
  - protractor config/protractor-conf.js --browser=firefox
